#!/usr/bin/env bash

# Get list of changed files
CHANGED_FILES="$(git diff --cached --name-only --diff-filter=ACM)"

# Check if any .js file changed
echo "$CHANGED_FILES" | grep '\.js$' >/dev/null 2>&1

# Check if the exit code of the last command is 0 (success)
if [[ $? == 0 ]]; then

    # Notify the user
    echo ""
    echo "githook: pre-commit: Running 'gulp js-lint' because a *.js file has changed"
    echo ""

    # Run gulp task
    gulp js-lint

    # Check if the exit code of the last command is 1 (error)
    if [[ $? == 1 ]]; then

        # Exit with error status code
        exit 1
    fi
fi

# Check if any .scss file changed
echo "$CHANGED_FILES" | grep '\.scss$' >/dev/null 2>&1

# Check if the exit code of the last command is 0 (success)
if [[ $? == 0 ]]; then

    # Notify the user
    echo ""
    echo "githook: pre-commit: Running 'gulp scss-lint' because a *.scss file has changed"
    echo ""

    # Run gulp task
    gulp css-lint

    # Check if the exit code of the last command is 1 (error)
    if [[ $? == 1 ]]; then

        # Exit with error status code
        exit 1
    fi
fi

# Exit with success status code
exit 0
