#!/usr/bin/env bash

#
# Prepends the branch name to the commit message
# 
 
# Get current branch name
BRANCH_NAME=$(git symbolic-ref --short HEAD) 

if [ -n "$BRANCH_NAME" ] && [ "$BRANCH_NAME" != "(no branch)" ] && [ "$BRANCH_NAME" != "master" ]; then
    chmod 0777 $1
    sed -i.bak -e "1s#^#$BRANCH_NAME: #" $1
    chmod 0777 $1
fi
