#!/usr/bin/env bash

CHANGED_FILES="$(git diff --cached --name-only --diff-filter=ACM)"

echo "$CHANGED_FILES" | grep -E '\.(md|css|scss|js|json)$' >/dev/null 2>&1

if [[ $? == 0 ]]; then

    echo ""
    echo "githook: pre-commit: Running 'npm run codestyleIsValid' because a *.{md,css,scss,js,json} file has changed"
    echo ""

    npm run codestyleIsValid >/dev/null 2>&1

    if [[ $? == 1 ]]; then

        echo ""
        echo "githook: pre-commit: Running 'npm run codestyle' because a *.{md,css,scss,js,json} file has changed"
        echo ""
        npm run codestyle

        echo ""
        echo "githook: pre-commit: Codestyle was automatically fixed, re-add files to Git and commit again"
        echo ""

        exit 1
    fi
fi

echo "$CHANGED_FILES" | grep -E '\.(scss|js)$' >/dev/null 2>&1

if [[ $? == 0 ]]; then

    echo ""
    echo "githook: pre-commit: Running 'npm run codequality' because a *.{scss,js} file has changed"
    echo ""

    npm run codequality

    if [[ $? == 1 ]]; then
        # Exit with error status code
        exit 1
    fi
fi

exit 0
